services: # https://docs.docker.com/compose/compose-file/
  ubuntu:
    build:
      context: .
      dockerfile: ubuntu.dockerfile
    volumes: # https://docs.docker.com/storage/volumes/#use-a-volume-with-docker-compose
      - type: bind  # https://docs.docker.com/storage/bind-mounts/#use-a-bind-mount-with-compose
        source: ..
        target: /project
    entrypoint: bash /project/script/run-tests.sh

  ubuntu-clang:
    extends: ubuntu
    environment:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
