version: '3.9' # https://docs.docker.com/compose/compose-file/

services:
  ubuntu:
    build:
      context: .
      dockerfile: ubuntu.dockerfile
    volumes:
      - type: bind
        source: ..
        target: /project
    entrypoint: bash /project/script/run-tests.sh

  ubuntu-clang:
    extends: ubuntu
    environment:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
