name: Continuous Integration

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  run-tests-sh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # https://github.com/marketplace/actions/checkout
      - run: ./script/run-tests.sh
