name: Continuous Integration

on:
  push:
  pull_request:
    branches:
      - main

  workflow_dispatch: # https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
    inputs:
      build-type:
        description: 'Build type'
        default: 'Release'
        type: choice
        options:
          - 'Debug'
          - 'Release'
        required: true

      job-filter:
        description: 'Only run jobs containing this string'
        default: ''
        type: string
        required: false

      log-level:
        description: 'Log level'
        default: 'info'
        type: choice
        options:
          - 'error'
          - 'warning'
          - 'info'
          - 'debug'
          - 'trace'
        required: false

env:
  DEFAULT_BUILD_TYPE: 'Debug'
  DEFAULT_JOB_FILTER: 'linux'
  DEFAULT_LOG_LEVEL: 'trace'
  RENDER_HEADLESS: true

jobs:
  cfg:
    runs-on: ubuntu-latest
    outputs: # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
      build-type: ${{ steps.build-type.outputs.build-type }}
      job-filter: ${{ steps.job-filter.outputs.job-filter }}
    steps:
      - id: build-type
        name: ${{ github.action }}
        run: |
          build_type='${{ github.event.inputs.build-type }}'
          build_type=${build_type:-$DEFAULT_BUILD_TYPE}
          echo "build-type=$build_type" | tee -a "$GITHUB_OUTPUT"

      - id: job-filter
        name: ${{ github.action }}
        run: |
          job_filter='${{ github.event.inputs.job-filter }}'
          job_filter=${job_filter:-$DEFAULT_JOB_FILTER}
          echo "job-filter=$job_filter" | tee -a "$GITHUB_OUTPUT"

      - id: log-level
        name: ${{ github.action }}
        run: |
          log_level='${{ github.event.inputs.log-level }}'
          log_level=${log_level:-$DEFAULT_LOG_LEVEL}
          echo "log-level=$log_level" | tee -a "$GITHUB_OUTPUT"

  run-docker-tests-bash:
    if: contains('run-docker-tests-bash', needs.cfg.outputs.job-filter)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # https://github.com/marketplace/actions/checkout
      - run: script/run-docker-tests.bash

  native-windows:
    if: contains('native-windows', needs.cfg.outputs.job-filter)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test & package
        run: |
          cmake -S . -B build/$BUILD_TYPE
          cmake --build build/$BUILD_TYPE --parallel --target all-unit build-package --config $env:BUILD_TYPE
      - uses: actions/upload-artifact@v3  # https://github.com/actions/upload-artifact
        with:
          name: package-${{ github.job }}
          path: build/ci/*.tar.xz
    needs: cfg
    env:
      BUILD_TYPE: ${{ needs.cfg.outputs.build-type }}
      LOG_LEVEL: ${{ needs.cfg.outputs.log-level }}

  native-macos:
    if: contains('native-macos', needs.cfg.outputs.job-filter)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test & package
        run: |
          cmake -S . -B build/$BUILD_TYPE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          cmake --build build/$BUILD_TYPE --parallel --target all-unit build-package
      - uses: actions/upload-artifact@v3
        with:
          name: package-${{ github.job }}
          path: build/ci/*.tar.xz
    needs: cfg
    env:
      BUILD_TYPE: ${{ needs.cfg.outputs.build-type }}
      LOG_LEVEL: ${{ needs.cfg.outputs.log-level }}

  native-linux:
    if: contains('native-linux', needs.cfg.outputs.job-filter)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test & package
        run: |
          cmake -S . -B build/$BUILD_TYPE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          cmake --build build/$BUILD_TYPE --parallel --target all-unit build-package
      - uses: actions/upload-artifact@v3
        with:
          name: package-${{ github.job }}
          path: build/ci/*.tar.xz

    needs: cfg
    env:
      BUILD_TYPE: ${{ needs.cfg.outputs.build-type }}
      LOG_LEVEL: ${{ needs.cfg.outputs.log-level }}
