name: Continuous Integration

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  run-docker-tests-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # https://github.com/marketplace/actions/checkout
      - run: script/run-docker-tests.bash

  native-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cmake -S . -B build/ci
          cmake --build build/ci --parallel --target all-unit build-package --config Release
      - uses: actions/upload-artifact@v3  # https://github.com/actions/upload-artifact
        with:
          name: package-${{ github.job }}
          path: build/ci/*.tar.xz

  native-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cmake -S . -B build/ci -DCMAKE_BUILD_TYPE=Release
          cmake --build build/ci --parallel --target all-unit build-package
      - uses: actions/upload-artifact@v3
        with:
          name: package-${{ github.job }}
          path: build/ci/*.tar.xz

  native-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cmake -S . -B build/ci -DCMAKE_BUILD_TYPE=Release
          cmake --build build/ci --parallel --target all-unit build-package
      - uses: actions/upload-artifact@v3
        with:
          name: package-${{ github.job }}
          path: build/ci/*.tar.xz
